version: '3'

services:
  sails:
    build: .
    container_name: sails-server
    command: sails lift
    ports:
      - 1337:1337
    volumes:
      - ./sails-backend:/code
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes: 
      - ./db_sails:/var/lib/mongodb/data
    ports:
      - "27017:27017"
